### ISSUE TITLE
pip installation not working

### ISSUE THREAD

**Issue by mads-bertelsen** [PaNOSC-ViNYL/libpyvinyl#16]
python -m pip install libpyvinyl fails with:

```
ERROR: Command errored out with exit status 1:
     command: /anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-2qehcxoy/libpyvinyl/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-2qehcxoy/libpyvinyl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-xhf01iyh
         cwd: /private/tmp/pip-install-2qehcxoy/libpyvinyl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-2qehcxoy/libpyvinyl/setup.py", line 3, in <module>
        with open('requirements.txt', 'r') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems the requirement file is being read at the install stage on the users pc, where it was intended to just be used when setting up the package for pip. Maybe requirements should go in the manifest file?

**Comment by CFGrote** [comment]
fixed by b1203481287def77809f719e7dc6f117a65aef18 .

**Comment by CFGrote** [comment]
@JunCEEE , is this an issue again? Or why did you assign me?

**Comment by JunCEEE** [comment]
> @JunCEEE , is this an issue again? Or why did you assign me?

Hi Carsten, sorry for the disturbance. I think I didn't assign it. I just closed it since it's not a problem anymore. Alles gut.
