### ISSUE TITLE
Unexpected error when set a float value

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/libpyvinyl#51]
When run this piece of code:
```py
diver_value = get_divergence_from_beam_diameter(photon_energy.value, diameter.value)
divergence.value = diver_value

def get_divergence_from_beam_diameter(E, beam_diameter_fwhm):
    """Calculate the divergence (radian) from and photon energy (eV) beam_diameter (m)"""
    # The rms of the amplitude distribution (Gaussian)
    E = Quantity(E, Unit("eV"))
    beam_waist = beam_diameter_fwhm / np.sqrt(2.0 * np.log(2.0))
    theta = 2.0 * hbar * c / beam_waist / E.to("joule").magnitude

    return theta
```

Got the following error, which is unexpected:
```
Traceback (most recent call last):
  File "test_GaussianSourceCalculator.py", line 8, in <module>
    calculator = GaussianSourceCalculator("gaussian_source",WPG_path)
  File "/gpfs/exfel/data/user/juncheng/SimExLite/SimExLite/SourceCalculators/GaussianSourceCalculator.py", line 28, in __init__
    super().__init__(
  File "/gpfs/exfel/data/user/juncheng/libpyvinyl/libpyvinyl/BaseCalculator.py", line 127, in __init__
    self.parameters = parameters
  File "/gpfs/exfel/data/user/juncheng/libpyvinyl/libpyvinyl/BaseCalculator.py", line 166, in parameters
    self.set_parameters(value)
  File "/gpfs/exfel/data/user/juncheng/libpyvinyl/libpyvinyl/BaseCalculator.py", line 173, in set_parameters
    self.init_parameters()
  File "/gpfs/exfel/data/user/juncheng/SimExLite/SimExLite/SourceCalculators/GaussianSourceCalculator.py", line 91, in init_parameters
    divergence.value = diver_value
  File "/gpfs/exfel/data/user/juncheng/libpyvinyl/libpyvinyl/Parameters/Parameter.py", line 235, in value
    self.__check_compatibility(value)
  File "/gpfs/exfel/data/user/juncheng/libpyvinyl/libpyvinyl/Parameters/Parameter.py", line 219, in __check_compatibility
    raise TypeError(
TypeError: New value of type <class 'numpy.float64'> is different from <class 'pint.quantity.Quantity'> previously defined
```
@shervin86  Could you please have a look at it? I guess it's because only `float` instead of `numpy.float64` was accepted. Maybe the solution is to show a more clear instruction in the error or accept numpy types as well.

**Comment by JunCEEE** [comment]
@JunCEEE Add testing in libpyvinyl

**Comment by JunCEEE** [comment]
@shervin86 tests added. It throws errors now.
https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/52/commits/9bde583b8b05383b9ac660e7b4d0ebd5ae3a40bf
